In [1]:
import numpy as np
import pandas as pd


### Загрузка Train/Test

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train

area  perimeter  major_axis  minor_axis  eccentricity   eqdiasq  \
0      75516  1731.4840    411.7352    245.7620        0.8023  310.0806   
1      98903  1374.4370    477.2451    269.7676        0.8249  354.8622   
2      84746  1311.1570    482.7735    235.9040        0.8725  328.4843   
3      98184  1463.1680    434.3769    292.6472        0.7390  353.5700   
4      94170  1267.7271    440.1109    278.4162        0.7745  346.2672   
...      ...        ...         ...         ...           ...       ...   
1283  103151  2145.1340    499.3782    280.9169        0.8268  362.4030   
1284   54322  1569.1990    363.6869    217.1759        0.8021  262.9922   
1285   69080  1713.4390    434.3565    213.7013        0.8706  296.5727   
1286   83490  1161.5470    448.3226    251.6644        0.8276  326.0410   
1287   63091  1058.6920    412.6924    199.5693        0.8753  283.4254   

      solidity  convex_area  extent  aspect_ratio  roundness  compactness  \
0       0.9148        82546  0.7169        1.6753     0.3165       0.7531   
1       0.9585       103181  0.7679        1.7691     0.6579       0.7436   
2       0.9121        92914  0.7162        2.0465     0.6195       0.6804   
3       0.9543       102890  0.7316        1.4843     0.5763       0.8140   
4       0.9643        97656  0.6836        1.5808     0.7363       0.7868   
...        ...          ...     ...           ...        ...          ...   
1283    0.9193       112202  0.7205        1.7777     0.2817       0.7257   
1284    0.8557        63481  0.6645        1.6746     0.2772       0.7231   
1285    0.9217        74947  0.6828        2.0325     0.2957       0.6828   
1286    0.9437        88472  0.6826        1.7814     0.7776       0.7272   
1287    0.9611        65645  0.7620        2.0679     0.7074       0.6868   

      shapefactor_1  shapefactor_2  shapefactor_3  shapefactor_4  target  
0            0.0055         0.0033         0.5672         0.9502       1  
1            0.0048         0.0027         0.5529         0.9781       0  
2            0.0057         0.0028         0.4630         0.9474       1  
3            0.0044         0.0030         0.6625         0.9834       0  
4            0.0047         0.0030         0.6190         0.9785       0  
...             ...            ...            ...            ...     ...  
1283         0.0048         0.0027         0.5267         0.9362       0  
1284         0.0067         0.0040         0.5229         0.8757       1  
1285         0.0063         0.0031         0.4662         0.9476       1  
1286         0.0054         0.0030         0.5289         0.9422       0  
1287         0.0065         0.0032         0.4717         0.9753       1  

[1288 rows x 17 columns]

In [4]:
train.iloc[:,:-1]

area  perimeter  major_axis  minor_axis  eccentricity   eqdiasq  \
0      75516  1731.4840    411.7352    245.7620        0.8023  310.0806   
1      98903  1374.4370    477.2451    269.7676        0.8249  354.8622   
2      84746  1311.1570    482.7735    235.9040        0.8725  328.4843   
3      98184  1463.1680    434.3769    292.6472        0.7390  353.5700   
4      94170  1267.7271    440.1109    278.4162        0.7745  346.2672   
...      ...        ...         ...         ...           ...       ...   
1283  103151  2145.1340    499.3782    280.9169        0.8268  362.4030   
1284   54322  1569.1990    363.6869    217.1759        0.8021  262.9922   
1285   69080  1713.4390    434.3565    213.7013        0.8706  296.5727   
1286   83490  1161.5470    448.3226    251.6644        0.8276  326.0410   
1287   63091  1058.6920    412.6924    199.5693        0.8753  283.4254   

      solidity  convex_area  extent  aspect_ratio  roundness  compactness  \
0       0.9148        82546  0.7169        1.6753     0.3165       0.7531   
1       0.9585       103181  0.7679        1.7691     0.6579       0.7436   
2       0.9121        92914  0.7162        2.0465     0.6195       0.6804   
3       0.9543       102890  0.7316        1.4843     0.5763       0.8140   
4       0.9643        97656  0.6836        1.5808     0.7363       0.7868   
...        ...          ...     ...           ...        ...          ...   
1283    0.9193       112202  0.7205        1.7777     0.2817       0.7257   
1284    0.8557        63481  0.6645        1.6746     0.2772       0.7231   
1285    0.9217        74947  0.6828        2.0325     0.2957       0.6828   
1286    0.9437        88472  0.6826        1.7814     0.7776       0.7272   
1287    0.9611        65645  0.7620        2.0679     0.7074       0.6868   

      shapefactor_1  shapefactor_2  shapefactor_3  shapefactor_4  
0            0.0055         0.0033         0.5672         0.9502  
1            0.0048         0.0027         0.5529         0.9781  
2            0.0057         0.0028         0.4630         0.9474  
3            0.0044         0.0030         0.6625         0.9834  
4            0.0047         0.0030         0.6190         0.9785  
...             ...            ...            ...            ...  
1283         0.0048         0.0027         0.5267         0.9362  
1284         0.0067         0.0040         0.5229         0.8757  
1285         0.0063         0.0031         0.4662         0.9476  
1286         0.0054         0.0030         0.5289         0.9422  
1287         0.0065         0.0032         0.4717         0.9753  

[1288 rows x 16 columns]

In [5]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
#fit the values to the function 
val = train.iloc[:,-1].values
train = std_scaler.fit_transform(train.iloc[:,:-1].values)
train = pd.DataFrame(train)
train['target'] = val
train

0         1         2         3         4         5         6  \
0    -0.362942  0.821283 -1.091876  0.229829 -0.764019 -0.320037 -0.527198   
1     1.451985 -0.132792  0.951740  1.027978 -0.303430  1.389711  0.371127   
2     0.353344 -0.301884  1.124202 -0.097934  0.666660  0.382610 -0.582701   
3     1.396188  0.104309 -0.385556  1.788689 -2.054077  1.340375  0.284789   
4     1.084685 -0.417934 -0.206681  1.315530 -1.330585  1.061556  0.490356   
...        ...       ...       ...       ...       ...       ...       ...   
1283  1.781648  1.926608  1.642194  1.398675 -0.264708  1.677616 -0.434693   
1284 -2.007684  0.387637 -2.590769 -0.720615 -0.768096 -2.117858 -1.742096   
1285 -0.862402  0.773064 -0.386193 -0.836140  0.627938 -0.835765 -0.385357   
1286  0.255873 -0.701661  0.049487  0.426074 -0.248404  0.289326  0.066889   
1287 -1.327173 -0.976502 -1.062016 -1.306007  0.723725 -1.337725  0.424575   

             7         8         9        10        11        12        13  \
0    -0.209070  0.023367 -0.926218 -1.207980  0.911809 -0.241093  0.868914   
1     1.373836  1.011546 -0.531657  0.412841  0.692705 -1.174008 -0.941538   
2     0.586257  0.009804  0.635198  0.230534 -0.764911  0.025454 -0.639796   
3     1.351514  0.308195 -1.729640  0.025439  2.316380 -1.707102 -0.036312   
4     0.950015 -0.621855 -1.323722  0.785051  1.689051 -1.307281 -0.036312   
...        ...       ...       ...       ...       ...       ...       ...   
1283  2.065835  0.093121 -0.495482 -1.373195  0.279868 -1.174008 -0.941538   
1284 -1.671542 -0.991938 -0.929162 -1.394559  0.219902  1.358190  2.981108   
1285 -0.791987 -0.637356  0.576308 -1.306729 -0.709559  0.825096  0.265430   
1286  0.245512 -0.641232 -0.479919  0.981125  0.314463 -0.374366 -0.036312   
1287 -1.505542  0.897227  0.725214  0.647846 -0.617305  1.091643  0.567172   

            14        15  target  
0     0.898470 -0.103699       1  
1     0.669632  0.446052       0  
2    -0.769005 -0.158871       1  
3     2.423521  0.550485       0  
4     1.727406  0.453934       0  
...        ...       ...     ...  
1283  0.250363 -0.379559       0  
1284  0.189553 -1.571672       1  
1285 -0.717797 -0.154930       1  
1286  0.285569 -0.261333       0  
1287 -0.629782  0.390880       1  

[1288 rows x 17 columns]

### Используем PyTorch. Создаем DataLoader на тензорах.

In [6]:
import torch
import torchvision
from IPython.display import clear_output
from matplotlib import pyplot as plt
from torch import nn
from torch.nn import functional as F
import time
from torch.utils.data import DataLoader, Dataset, Subset, TensorDataset
from sklearn.model_selection import train_test_split

In [7]:
train, validation = train_test_split(train, test_size=0.3)
train_target = torch.tensor(train['target'].values.astype(np.float32))
train = torch.tensor(train.drop('target', axis = 1).values.astype(np.float32)) 
train_tensor = TensorDataset(train, train_target) 
train_loader = DataLoader(dataset = train_tensor, batch_size = 64, shuffle = True)


validation_target = torch.tensor(validation['target'].values.astype(np.float32))
validation = torch.tensor(validation.drop('target', axis = 1).values.astype(np.float32)) 
validation_tensor = TensorDataset(validation, validation_target) 
validation_tensor

In [8]:
train_tensor.tensors[0].shape

torch.Size([901, 16])

In [9]:
validation_tensor.tensors[0].shape

torch.Size([387, 16])

In [10]:
random_batch = next(iter(train_loader))
_image, _label = random_batch[0][0], random_batch[1][0]


In [11]:
random_batch[0]

tensor([[ 0.6856, -0.3378,  1.2985,  ..., -1.2433, -0.5722,  0.7653],
        [-0.0290, -0.6164,  0.0527,  ..., -0.3381, -0.0905,  0.5032],
        [ 1.3483,  1.6676,  1.6796,  ..., -1.2433, -0.2441,  0.3889],
        ...,
        [-0.3575, -0.9659, -0.8954,  ...,  0.2654,  0.6344,  0.7988],
        [ 0.6697, -0.3725,  1.2872,  ..., -1.2433, -0.5786,  0.6116],
        [ 0.1624,  1.7232,  0.3307,  ..., -0.0363, -0.1625, -0.7796]])

### Создаем модельку и обучаем ее. 

In [12]:
# use GPU if available
device = torch.device("cpu")
device

device(type='cpu')

In [123]:
m = nn.LogSigmoid()
input = torch.randn(2)
output = m(input)
output

tensor([-0.5927, -0.1744])

In [124]:
# Creating model instance
default_dtype = torch.float32
model_task_1 = nn.Sequential(
    nn.Linear(16,1),
    nn.Sigmoid()

)
model_task_1.to(device,default_dtype)

Sequential(
  (0): Linear(in_features=16, out_features=1, bias=True)
  (1): Sigmoid()
)

In [125]:
# do not change the code in the block below
# __________start of block__________
random_batch = next(iter(train_loader))
assert model_task_1 is not None, "Please, use `model_task_1` variable to store your model"

try:
    x = random_batch[0].to(device)
    y = random_batch[1].to(device)

    # compute outputs given inputs, both are variables
    y_predicted = model_task_1(x)
except Exception as e:
    print("Something is wrong with the model")
    raise e


assert y_predicted.shape[-1] == 1, "Model should predict 1 logits/probas"

print("Everything seems fine!")
# __________end of block__________

Everything seems fine!


In [130]:
# your code here
def train_model(model,train_loader,val_loader,loss_fn,optimizer,epochs: int, device=device):
    losses_train = []
    losses_test = []
    acc = []
    for epoch in range(epochs):
        start_time = time.time()
        model.train(True)
        for X,Y in train_loader:
            X,Y = X.to(device), Y.to(device)
            output=model(X)
            output=output.T[0]
            loss=loss_fn(output, Y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            losses_train.append(loss.item())
        model.train(False)
        with torch.no_grad():
            for X,Y in val_loader:
                X,Y = X.to(device), Y.to(device)
                output=model(X)
                loss=loss_fn(output[0], Y)
                losses_test.append(loss.item())
                y_pred = output.max(-1)[1]
                acc.append((y_pred==Y).to(default_dtype).mean().item())
        print(f'epoch {epoch+1}/{epochs}, {time.time()-start_time:.3f}s.')
        print(f'\t training loss: {losses_train[-1]:.6f}')
        print(f'\t validation loss: {losses_test[-1]:.6f}')
        print(f'\t val accuracy: {acc[-1]:.6f}')
optimizer = torch.optim.Adam(model_task_1.parameters(), lr=1e-3)
epochs=1000
train_model(model_task_1, train_loader,validation_tensor,nn.BCELoss(),optimizer,epochs,device)

epoch 1/1000, 0.068s.
	 training loss: 0.275899
	 validation loss: 0.089955
	 val accuracy: 0.000000
epoch 2/1000, 0.043s.
	 training loss: 0.130782
	 validation loss: 0.086170
	 val accuracy: 0.000000
epoch 3/1000, 0.044s.
	 training loss: 0.169995
	 validation loss: 0.080316
	 val accuracy: 0.000000
epoch 4/1000, 0.038s.
	 training loss: 0.095152
	 validation loss: 0.076437
	 val accuracy: 0.000000
epoch 5/1000, 0.046s.
	 training loss: 0.857777
	 validation loss: 0.074605
	 val accuracy: 0.000000
epoch 6/1000, 0.040s.
	 training loss: 0.335140
	 validation loss: 0.072756
	 val accuracy: 0.000000
epoch 7/1000, 0.044s.
	 training loss: 0.588116
	 validation loss: 0.069057
	 val accuracy: 0.000000
epoch 8/1000, 0.038s.
	 training loss: 0.221218
	 validation loss: 0.069453
	 val accuracy: 0.000000
epoch 9/1000, 0.036s.
	 training loss: 0.256365
	 validation loss: 0.068894
	 val accuracy: 0.000000
epoch 10/1000, 0.034s.
	 training loss: 0.339324
	 validation loss: 0.065693
	 val accuracy

In [20]:
for X,Y in validation_tensor.tensors:
    X,Y = X.to(device),Y.to(device)
    output = model_task_1(X)
    print(output,Y)

ValueError: too many values to unpack (expected 2)

In [23]:
for x,y in validation_tensor:
    print(x,y)

tensor([ 1.2470,  0.2020,  1.5914,  0.3070,  0.5525,  1.2076,  0.7144,  1.0312,
        -0.2576,  0.4665, -0.1573, -0.2368, -0.6409, -1.2433, -0.2617,  0.7318]) tensor(0.)
tensor([ 1.1215,  2.1751, -0.2933,  1.9696, -2.2029,  1.0949, -0.6834,  1.4614,
        -1.1043, -1.8020, -1.5835,  1.8505, -1.4406,  0.2654,  1.9050, -0.6121]) tensor(0.)
tensor([ 0.3606,  2.8114,  0.5605,  0.4085,  0.0328,  0.3895, -0.5704,  0.5896,
        -0.0503, -0.1897, -1.8850, -0.1445, -0.2411, -0.0363, -0.1737, -0.5884]) tensor(0.)
tensor([ 1.4563, -0.2560,  0.7129,  1.6094, -0.9923,  1.3935, -0.6711,  1.8206,
        -0.5366, -1.0966,  0.6355,  0.9764, -1.3073, -0.3381,  0.9657, -0.4209]) tensor(0.)
tensor([-0.7257, -0.3870, -1.1687, -0.4074, -0.1445, -0.6923,  0.1820, -0.8170,
        -0.0696, -0.3756, -0.1284,  0.4667,  0.1587,  0.5672,  0.4392,  0.3377]) tensor(1.)
tensor([-0.6331, -0.3718, -0.7686, -0.1424, -0.1710, -0.5961, -0.3771, -0.5487,
        -0.1975, -0.4038, -0.1080,  0.0907,  0.2920,  0.8689

In [159]:
validation_tensor.tensors[0][0]

tensor([-0.6876, -0.7572, -0.5749, -0.7124,  0.4445, -0.6527,  0.2827, -0.8068,
         0.5465,  0.3130,  0.5595, -0.2298,  0.4253, -0.0363, -0.2553,  0.3909])

In [ ]:
k=0
for r in validation_tensor:
    X = r[0]
    X = X.to(device)
    Y = r[1]
    o = model_task_1(X)
    if o>0.5:
        o=1
    else: o=0
    if o==Y:
        k+=1
print(k/len(validation_tensor))

0.8475452196382429
