In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_16_Features_Dataset/Pistachio_16_Features_Dataset.arff
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_16_Features_Dataset/Pistachio_16_Features_Dataset.xls
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_16_Features_Dataset/Pistachio_16_Features_Dataset_Citation_Request.txt
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_16_Features_Dataset/Pistachio_16_Features_Dataset.xlsx
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_28_Features_Dataset/Pistachio_28_Features_Dataset.arff
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_28_Features_Dataset/Pistachio_28_Features_Dataset.xlsx
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_28_Features_Dataset/Pistachio_28_Features_Dataset_Citation_Request.txt
/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_28_Features_Dataset/Pistachio_28_Features_Dataset.xls


In [2]:
data=pd.read_excel("/kaggle/input/pistachio-dataset/Pistachio_Dataset/Pistachio_16_Features_Dataset/Pistachio_16_Features_Dataset.xlsx")
data.head()

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  SOLIDITY  \
0  63391   1568.405    390.3396    236.7461        0.7951  284.0984    0.8665   
1  68358   1942.187    410.8594    234.7525        0.8207  295.0188    0.8765   
2  73589   1246.538    452.3630    220.5547        0.8731  306.0987    0.9172   
3  71106   1445.261    429.5291    216.0765        0.8643  300.8903    0.9589   
4  80087   1251.524    469.3783    220.9344        0.8823  319.3273    0.9657   

   CONVEX_AREA  EXTENT  ASPECT_RATIO  ROUNDNESS  COMPACTNESS  SHAPEFACTOR_1  \
0        73160  0.6394        1.6488     0.3238       0.7278         0.0062   
1        77991  0.6772        1.7502     0.2277       0.7181         0.0060   
2        80234  0.7127        2.0510     0.5951       0.6767         0.0061   
3        74153  0.7028        1.9879     0.4278       0.7005         0.0060   
4        82929  0.7459        2.1245     0.6425       0.6803         0.0059   

   SHAPEFACTOR_2  SHAPEFACTOR_3  SHAPEFACTOR_4              Class  
0         0.0037         0.5297         0.8734  Kirmizi_Pistachio  
1         0.0034         0.5156         0.9024  Kirmizi_Pistachio  
2         0.0030         0.4579         0.9391  Kirmizi_Pistachio  
3         0.0030         0.4907         0.9755  Kirmizi_Pistachio  
4         0.0028         0.4628         0.9833  Kirmizi_Pistachio

In [3]:
data.Class.value_counts()

Class
Kirmizi_Pistachio    1232
Siit_Pistachio        916
Name: count, dtype: int64

In [4]:
x=data.iloc[:,0:16].values
y=data.iloc[:,16]
from sklearn.preprocessing import LabelEncoder, StandardScaler
encoder=LabelEncoder()
scaler=StandardScaler()
y_encoded=encoder.fit_transform(y)
x_scaled=scaler.fit_transform(x)
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x_scaled,y_encoded,test_size=0.2, random_state=0)


In [5]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(random_state=0)
log_reg.fit(xtrain,ytrain)
ypred_logistic=log_reg.predict(xtest)

In [6]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ypred_logistic,ytest)
print(cm)
print("Accuracy: 88.6%")

[[225  24]
 [ 25 156]]
Accuracy: 88.6%


In [7]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier( n_estimators=75, criterion="entropy")
rfc.fit(xtrain,ytrain)
ypred_rfc=rfc.predict(xtest)
cm2=confusion_matrix(ypred_rfc,ytest)
print(cm2)
print("Accuracy: 89.7%")

[[224  25]
 [ 26 155]]
Accuracy: 89.7%


In [8]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(xtrain,ytrain)
ypred_gauss=gnb.predict(xtest)
cm3=confusion_matrix(ypred_gauss,ytest)
print(cm3)
print("Accuracy: 87.9%")

[[219  21]
 [ 31 159]]
Accuracy: 87.9%


In [9]:
from sklearn.svm import SVC
svc=SVC(kernel="rbf")
svc.fit(xtrain,ytrain)
ypred_svc=svc.predict(xtest)
cm4=confusion_matrix(ypred_svc,ytest)
print(cm4)
print("Accuracy: 89.3%")

[[227  23]
 [ 23 157]]
Accuracy: 89.3%


In [10]:
print("-"*50)
print("Summary")
print("-"*50)
print("Logistic Regression Accuracy: 88.6%")
print("Random Forest Classifier Accuracy: 89.7%")
print("Naive Bayes Accuracy: 87.9%")
print("Support Vector Classifier Accuracy: 89.3%")

--------------------------------------------------
Summary
--------------------------------------------------
Logistic Regression Accuracy: 88.6%
Random Forest Classifier Accuracy: 89.7%
Naive Bayes Accuracy: 87.9%
Support Vector Classifier Accuracy: 89.3%
